export const REPOSITORIES = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  SUPER_USER_REPOSITORY: 'SUPER_USER_REPOSITORY',
  LOGIN_TOKEN_REPOSITORY: 'LOGIN_TOKEN_REPOSITORY',
  NUTRITION_REPOSITORY: 'NUTRITION_REPOSITORY',
  EXERCISE_REPOSITORY: 'EXERCISE_REPOSITORY',
  USER_LOCATION_REPOSITORY: 'USER_LOCATION_REPOSITORY',
  SELECTED_EXERCISE_REPOSITORY: 'SELECTED_EXERCISE_REPOSITORY',
  WORKOUT_REPOSITORY: 'WORKOUT_REPOSITORY',
};
